---
# Install Nginx

- name: Install nginx from a .deb package
  apt:
    deb: http://nginx.org/packages/debian/pool/nginx/n/nginx/nginx_1.12.0-1~stretch_amd64.deb
# Create /etc/nginx/conf.d/ directory
- name: Create nginx directory structure
  file: path=/etc/nginx/conf.d/
   state=directory
   mode=0755
# Deploy kibana.conf with FQDN
- name: Setup Nginx reverse proxy for kibana
  template:
   src=kibana.conf.j2
   dest=/etc/nginx/conf.d/default.conf
   owner=root
   group=root
   mode=0644
  register: nginx_needs_restart
# Enable nginx service
- name: Enabling Nginx service
  systemd:
   name: nginx
   enabled: yes
# Start Nginx service
- name: Starting Nginx service
  systemd:
   name: nginx
   state: started
   daemon_reload: yes
# Install Pexpect to handle promts of the terminal
- name: Installing Python Pexpect from .deb package
  apt:
    deb: http://ftp.br.debian.org/debian/pool/main/p/pexpect/python-pexpect_4.2.1-1_all.deb
# Writes the create user script in the temp directory
- name: Create kibana admin user
  template:
   src=kibanaAdmin.j2
   dest=/tmp/createUser
   owner=root
   group=root
   mode=0744
# Runs the script to create Kibana admin user
- name: Create Kibana admin user
  expect:
     command: bash /tmp/createUser
     responses:
       'Password:' : "{{kibana_password}}"
# Restart Nginx service
- name: Restart Nginx service
  systemd:
   name: nginx
   state: reloaded
   daemon_reload: yes